# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://fury252.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: "André Rodrigues"
lang: en
title: "Porque não?"
description: A space where I share what might be useful to others.

# Build settings
plugins:
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
